version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: delivery
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: delivery
      POSTGRES_DB: delivery
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge